sonar.issue.ignore.multicriteria=e1,e2
sonar.issue.ignore.multicriteria.e1.ruleKey=javascript:S1313
sonar.issue.ignore.multicriteria.e1.resourceKey=test/**/*
sonar.issue.ignore.multicriteria.e2.ruleKey=javascript:S2068
sonar.issue.ignore.multicriteria.e2.resourceKey=test/**/*
